# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='messages',
            new_name='message',
        ),
    ]
